export const flagEmojis = [
  { emoji: '🏳️', name: 'Weiße Flagge' },
  { emoji: '🏴', name: 'Schwarze Flagge' },
  { emoji: '🏁', name: 'Zielflagge' },
  { emoji: '🚩', name: 'Rote Flagge' },
  { emoji: '🏳️‍🌈', name: 'Regenbogenflagge' },
  { emoji: '🏴‍☠️', name: 'Piratenflagge' },
  { emoji: '🇦🇫', name: 'Afghanistan' },
  { emoji: '🇦🇱', name: 'Albanien' },
  { emoji: '🇩🇿', name: 'Algerien' },
  { emoji: '🇦🇩', name: 'Andorra' },
  { emoji: '🇦🇴', name: 'Angola' },
  { emoji: '🇦🇬', name: 'Antigua und Barbuda' },
  { emoji: '🇦🇷', name: 'Argentinien' },
  { emoji: '🇦🇲', name: 'Armenien' },
  { emoji: '🇦🇺', name: 'Australien' },
  { emoji: '🇦🇹', name: 'Österreich' },
  { emoji: '🇦🇿', name: 'Aserbaidschan' },
  { emoji: '🇧🇸', name: 'Bahamas' },
  { emoji: '🇧🇭', name: 'Bahrain' },
  { emoji: '🇧🇩', name: 'Bangladesch' },
  { emoji: '🇧🇧', name: 'Barbados' },
  { emoji: '🇧🇾', name: 'Belarus' },
  { emoji: '🇧🇪', name: 'Belgien' },
  { emoji: '🇧🇿', name: 'Belize' },
  { emoji: '🇧🇯', name: 'Benin' },
  { emoji: '🇧🇹', name: 'Bhutan' },
  { emoji: '🇧🇴', name: 'Bolivien' },
  { emoji: '🇧🇦', name: 'Bosnien und Herzegowina' },
  { emoji: '🇧🇼', name: 'Botswana' },
  { emoji: '🇧🇷', name: 'Brasilien' },
  { emoji: '🇧🇳', name: 'Brunei' },
  { emoji: '🇧🇬', name: 'Bulgarien' },
  { emoji: '🇧🇫', name: 'Burkina Faso' },
  { emoji: '🇧🇮', name: 'Burundi' },
  { emoji: '🇨🇻', name: 'Cabo Verde' },
  { emoji: '🇰🇭', name: 'Kambodscha' },
  { emoji: '🇨🇲', name: 'Kamerun' },
  { emoji: '🇨🇦', name: 'Kanada' },
  { emoji: '🇨🇫', name: 'Zentralafrikanische Republik' },
  { emoji: '🇹🇩', name: 'Tschad' },
  { emoji: '🇨🇱', name: 'Chile' },
  { emoji: '🇨🇳', name: 'China' },
  { emoji: '🇨🇴', name: 'Kolumbien' },
  { emoji: '🇰🇲', name: 'Komoren' },
  { emoji: '🇨🇬', name: 'Kongo' },
  { emoji: '🇨🇩', name: 'DR Kongo' },
  { emoji: '🇨🇷', name: 'Costa Rica' },
  { emoji: '🇨🇮', name: 'Elfenbeinküste' },
  { emoji: '🇭🇷', name: 'Kroatien' },
  { emoji: '🇨🇺', name: 'Kuba' },
  { emoji: '🇨🇾', name: 'Zypern' },
  { emoji: '🇨🇿', name: 'Tschechien' },
  { emoji: '🇩🇰', name: 'Dänemark' },
  { emoji: '🇩🇯', name: 'Dschibuti' },
  { emoji: '🇩🇲', name: 'Dominica' },
  { emoji: '🇩🇴', name: 'Dominikanische Republik' },
  { emoji: '🇪🇨', name: 'Ecuador' },
  { emoji: '🇪🇬', name: 'Ägypten' },
  { emoji: '🇸🇻', name: 'El Salvador' },
  { emoji: '🇬🇶', name: 'Äquatorialguinea' },
  { emoji: '🇪🇷', name: 'Eritrea' },
  { emoji: '🇪🇪', name: 'Estland' },
  { emoji: '🇸🇿', name: 'Eswatini' },
  { emoji: '🇪🇹', name: 'Äthiopien' },
  { emoji: '🇪🇺', name: 'Europäische Union' },
  { emoji: '🇫🇯', name: 'Fidschi' },
  { emoji: '🇫🇮', name: 'Finnland' },
  { emoji: '🇫🇷', name: 'Frankreich' },
  { emoji: '🇬🇦', name: 'Gabun' },
  { emoji: '🇬🇲', name: 'Gambia' },
  { emoji: '🇬🇪', name: 'Georgien' },
  { emoji: '🇩🇪', name: 'Deutschland' },
  { emoji: '🇬🇭', name: 'Ghana' },
  { emoji: '🇬🇷', name: 'Griechenland' },
  { emoji: '🇬🇩', name: 'Grenada' },
  { emoji: '🇬🇹', name: 'Guatemala' },
  { emoji: '🇬🇳', name: 'Guinea' },
  { emoji: '🇬🇼', name: 'Guinea-Bissau' },
  { emoji: '🇬🇾', name: 'Guyana' },
  { emoji: '🇭🇹', name: 'Haiti' },
  { emoji: '🇭🇳', name: 'Honduras' },
  { emoji: '🇭🇺', name: 'Ungarn' },
  { emoji: '🇮🇸', name: 'Island' },
  { emoji: '🇮🇳', name: 'Indien' },
  { emoji: '🇮🇩', name: 'Indonesien' },
  { emoji: '🇮🇷', name: 'Iran' },
  { emoji: '🇮🇶', name: 'Irak' },
  { emoji: '🇮🇪', name: 'Irland' },
  { emoji: '🇮🇱', name: 'Israel' },
  { emoji: '🇮🇹', name: 'Italien' },
  { emoji: '🇯🇲', name: 'Jamaika' },
  { emoji: '🇯🇵', name: 'Japan' },
  { emoji: '🇯🇴', name: 'Jordanien' },
  { emoji: '🇰🇿', name: 'Kasachstan' },
  { emoji: '🇰🇪', name: 'Kenia' },
  { emoji: '🇰🇮', name: 'Kiribati' },
  { emoji: '🇽🇰', name: 'Kosovo' },
  { emoji: '🇰🇼', name: 'Kuwait' },
  { emoji: '🇰🇬', name: 'Kirgisistan' },
  { emoji: '🇱🇦', name: 'Laos' },
  { emoji: '🇱🇻', name: 'Lettland' },
  { emoji: '🇱🇧', name: 'Libanon' },
  { emoji: '🇱🇸', name: 'Lesotho' },
  { emoji: '🇱🇷', name: 'Liberia' },
  { emoji: '🇱🇾', name: 'Libyen' },
  { emoji: '🇱🇮', name: 'Liechtenstein' },
  { emoji: '🇱🇹', name: 'Litauen' },
  { emoji: '🇱🇺', name: 'Luxemburg' },
  { emoji: '🇲🇬', name: 'Madagaskar' },
  { emoji: '🇲🇼', name: 'Malawi' },
  { emoji: '🇲🇾', name: 'Malaysia' },
  { emoji: '🇲🇻', name: 'Malediven' },
  { emoji: '🇲🇱', name: 'Mali' },
  { emoji: '🇲🇹', name: 'Malta' },
  { emoji: '🇲🇭', name: 'Marshallinseln' },
  { emoji: '🇲🇷', name: 'Mauretanien' },
  { emoji: '🇲🇺', name: 'Mauritius' },
  { emoji: '🇲🇽', name: 'Mexiko' },
  { emoji: '🇫🇲', name: 'Mikronesien' },
  { emoji: '🇲🇩', name: 'Moldau' },
  { emoji: '🇲🇨', name: 'Monaco' },
  { emoji: '🇲🇳', name: 'Mongolei' },
  { emoji: '🇲🇪', name: 'Montenegro' },
  { emoji: '🇲🇦', name: 'Marokko' },
  { emoji: '🇲🇿', name: 'Mosambik' },
  { emoji: '🇲🇲', name: 'Myanmar' },
  { emoji: '🇳🇦', name: 'Namibia' },
  { emoji: '🇳🇷', name: 'Nauru' },
  { emoji: '🇳🇵', name: 'Nepal' },
  { emoji: '🇳🇱', name: 'Niederlande' },
  { emoji: '🇳🇿', name: 'Neuseeland' },
  { emoji: '🇳🇮', name: 'Nicaragua' },
  { emoji: '🇳🇪', name: 'Niger' },
  { emoji: '🇳🇬', name: 'Nigeria' },
  { emoji: '🇰🇵', name: 'Nordkorea' },
  { emoji: '🇲🇰', name: 'Nordmazedonien' },
  { emoji: '🇳🇴', name: 'Norwegen' },
  { emoji: '🇴🇲', name: 'Oman' },
  { emoji: '🇵🇰', name: 'Pakistan' },
  { emoji: '🇵🇼', name: 'Palau' },
  { emoji: '🇵🇸', name: 'Palästina' },
  { emoji: '🇵🇦', name: 'Panama' },
  { emoji: '🇵🇬', name: 'Papua-Neuguinea' },
  { emoji: '🇵🇾', name: 'Paraguay' },
  { emoji: '🇵🇪', name: 'Peru' },
  { emoji: '🇵🇭', name: 'Philippinen' },
  { emoji: '🇵🇱', name: 'Polen' },
  { emoji: '🇵🇹', name: 'Portugal' },
  { emoji: '🇶🇦', name: 'Katar' },
  { emoji: '🇷🇴', name: 'Rumänien' },
  { emoji: '🇷🇺', name: 'Russland' },
  { emoji: '🇷🇼', name: 'Ruanda' },
  { emoji: '🇰🇳', name: 'St. Kitts und Nevis' },
  { emoji: '🇱🇨', name: 'St. Lucia' },
  { emoji: '🇻🇨', name: 'St. Vincent und die Grenadinen' },
  { emoji: '🇼🇸', name: 'Samoa' },
  { emoji: '🇸🇲', name: 'San Marino' },
  { emoji: '🇸🇹', name: 'São Tomé und Príncipe' },
  { emoji: '🇸🇦', name: 'Saudi-Arabien' },
  { emoji: '🇸🇳', name: 'Senegal' },
  { emoji: '🇷🇸', name: 'Serbien' },
  { emoji: '🇸🇨', name: 'Seychellen' },
  { emoji: '🇸🇱', name: 'Sierra Leone' },
  { emoji: '🇸🇬', name: 'Singapur' },
  { emoji: '🇸🇰', name: 'Slowakei' },
  { emoji: '🇸🇮', name: 'Slowenien' },
  { emoji: '🇸🇧', name: 'Salomonen' },
  { emoji: '🇸🇴', name: 'Somalia' },
  { emoji: '🇿🇦', name: 'Südafrika' },
  { emoji: '🇰🇷', name: 'Südkorea' },
  { emoji: '🇸🇸', name: 'Südsudan' },
  { emoji: '🇪🇸', name: 'Spanien' },
  { emoji: '🇱🇰', name: 'Sri Lanka' },
  { emoji: '🇸🇩', name: 'Sudan' },
  { emoji: '🇸🇷', name: 'Suriname' },
  { emoji: '🇸🇪', name: 'Schweden' },
  { emoji: '🇨🇭', name: 'Schweiz' },
  { emoji: '🇸🇾', name: 'Syrien' },
  { emoji: '🇹🇼', name: 'Taiwan' },
  { emoji: '🇹🇯', name: 'Tadschikistan' },
  { emoji: '🇹🇿', name: 'Tansania' },
  { emoji: '🇹🇭', name: 'Thailand' },
  { emoji: '🇹🇱', name: 'Osttimor' },
  { emoji: '🇹🇬', name: 'Togo' },
  { emoji: '🇹🇴', name: 'Tonga' },
  { emoji: '🇹🇹', name: 'Trinidad und Tobago' },
  { emoji: '🇹🇳', name: 'Tunesien' },
  { emoji: '🇹🇷', name: 'Türkei' },
  { emoji: '🇹🇲', name: 'Turkmenistan' },
  { emoji: '🇹🇻', name: 'Tuvalu' },
  { emoji: '🇺🇬', name: 'Uganda' },
  { emoji: '🇺🇦', name: 'Ukraine' },
  { emoji: '🇦🇪', name: 'Vereinigte Arabische Emirate' },
  { emoji: '🇬🇧', name: 'Vereinigtes Königreich' },
  { emoji: '🇺🇳', name: 'Vereinte Nationen' },
  { emoji: '🇺🇸', name: 'Vereinigte Staaten' },
  { emoji: '🇺🇾', name: 'Uruguay' },
  { emoji: '🇺🇿', name: 'Usbekistan' },
  { emoji: '🇻🇺', name: 'Vanuatu' },
  { emoji: '🇻🇦', name: 'Vatikan' },
  { emoji: '🇻🇪', name: 'Venezuela' },
  { emoji: '🇻🇳', name: 'Vietnam' },
  { emoji: '🇾🇪', name: 'Jemen' },
  { emoji: '🇿🇲', name: 'Sambia' },
  { emoji: '🇿🇼', name: 'Simbabwe' },
]

export const personEmojis = [
  { emoji: '👦', name: 'Junge' },
  { emoji: '👧', name: 'Mädchen' },
  { emoji: '👨', name: 'Mann' },
  { emoji: '👩', name: 'Frau' },
  { emoji: '🧑', name: 'Person' },
  { emoji: '👴', name: 'Alter Mann' },
  { emoji: '👵', name: 'Alte Frau' },
  { emoji: '👶', name: 'Baby' },
  { emoji: '🧒', name: 'Kind' },
  { emoji: '👱‍♂️', name: 'Blonder Mann' },
  { emoji: '👱‍♀️', name: 'Blonde Frau' },
  { emoji: '🧔', name: 'Bartträger' },
  { emoji: '🤴', name: 'Prinz' },
  { emoji: '👸', name: 'Prinzessin' },
  { emoji: '🧙‍♂️', name: 'Zauberer' },
  { emoji: '🧙‍♀️', name: 'Zauberin' },
  { emoji: '🦸‍♂️', name: 'Superheld' },
  { emoji: '🦸‍♀️', name: 'Superheldin' },
  { emoji: '🧚‍♀️', name: 'Fee' },
  { emoji: '🧜‍♀️', name: 'Meerjungfrau' },
  { emoji: '🧝‍♀️', name: 'Elfe' },
  { emoji: '🤖', name: 'Roboter' },
  { emoji: '👽', name: 'Alien' },
  { emoji: '🎃', name: 'Kürbis' },
  { emoji: '🐱', name: 'Katze' },
  { emoji: '🐶', name: 'Hund' },
  { emoji: '🐻', name: 'Bär' },
  { emoji: '🐻‍❄️', name: 'Eisbär' },
  { emoji: '🦊', name: 'Fuchs' },
  { emoji: '🐸', name: 'Frosch' },
  { emoji: '🐼', name: 'Panda' },
  { emoji: '🦁', name: 'Löwe' },
  { emoji: '🐯', name: 'Tiger' },
  { emoji: '🦄', name: 'Einhorn' },
  { emoji: '🐺', name: 'Wolf' },
  { emoji: '🐨', name: 'Koala' },
  { emoji: '🐮', name: 'Kuh' },
  { emoji: '🐷', name: 'Schwein' },
  { emoji: '🐰', name: 'Hase' },
  { emoji: '🐸', name: 'Frosch' },
  { emoji: '🦋', name: 'Schmetterling' },
  { emoji: '🌸', name: 'Kirschblüte' },
  { emoji: '⭐', name: 'Stern' },
  { emoji: '🌙', name: 'Mond' },
  { emoji: '☀️', name: 'Sonne' },
  { emoji: '❤️', name: 'Herz' },
  { emoji: '🍓', name: 'Erdbeere' },
]
